// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";

import AuthenticationConcept from "./Authentication/AuthenticationConcept.ts";
import CalendarConcept from "./Calendar/CalendarConcept.ts";
import RecipeBookConcept from "./RecipeBook/RecipeBookConcept.ts";
import RecipesConcept from "./Recipes/RecipesConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import SnapshotConcept from "./Snapshot/SnapshotConcept.ts";

export type { default as AuthenticationConcept } from "./Authentication/AuthenticationConcept.ts";
export type { default as CalendarConcept } from "./Calendar/CalendarConcept.ts";
export type { default as RecipeBookConcept } from "./RecipeBook/RecipeBookConcept.ts";
export type { default as RecipesConcept } from "./Recipes/RecipesConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as SnapshotConcept } from "./Snapshot/SnapshotConcept.ts";

// Initialize the database connection
export const [db, client] = await getDb();

export const Authentication = Engine.instrumentConcept(new AuthenticationConcept(db));
export const Calendar = Engine.instrumentConcept(new CalendarConcept(db));
export const RecipeBook = Engine.instrumentConcept(new RecipeBookConcept(db));
export const Recipes = Engine.instrumentConcept(new RecipesConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const Snapshot = Engine.instrumentConcept(new SnapshotConcept(db));
