// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";

import AuthenticationConcept from "./Authentication/AuthenticationConcept.ts";
import CalendarConcept from "./Calendar/CalendarConcept.ts";
import DishesConcept from "./Dishes/DishesConcept.ts";
import RecipeConcept from "./Recipe/RecipeConcept.ts";
import RecipeBookConcept from "./RecipeBook/RecipeBookConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";

export type { default as AuthenticationConcept } from "./Authentication/AuthenticationConcept.ts";
export type { default as CalendarConcept } from "./Calendar/CalendarConcept.ts";
export type { default as DishesConcept } from "./Dishes/DishesConcept.ts";
export type { default as RecipeConcept } from "./Recipe/RecipeConcept.ts";
export type { default as RecipeBookConcept } from "./RecipeBook/RecipeBookConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";

// Initialize the database connection
export const [db, client] = await getDb();

export const Authentication = Engine.instrumentConcept(new AuthenticationConcept(db));
export const Calendar = Engine.instrumentConcept(new CalendarConcept(db));
export const Dishes = Engine.instrumentConcept(new DishesConcept(db));
export const Recipe = Engine.instrumentConcept(new RecipeConcept(db));
export const RecipeBook = Engine.instrumentConcept(new RecipeBookConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
